### ISSUE TITLE
CA-A01 antenna has an extra "deploy experiment" button in the right-click menu (From DMagicScienceAnimate)

### ISSUE THREAD

**Issue by raveloda** [raveloda/Coatl-Aerospace#1]

**Comment by CobaltWolf** [comment]
Why is it still using the DMSA module? I thought AnimateGeneric was fixed in 1.1.

**Comment by raveloda** [comment]
I am testing both options. So far it appears that the stock "oneShot"
option is still broken

**Comment by CobaltWolf** [comment]
Hrmm. Nobueno.

**Comment by raveloda** [comment]
Fixed using code by Jso!
`MODULE
    {
        name = ModuleAnimateGeneric
        animationName = deploy
        //isOneShot = true
        disableAfterPlaying = true
        startEventGUIName = Deploy
        endEventGUIName = Retract
        actionGUIName = Toggle Antenna
        allowAnimationWhileShielded = False
    }`
